language: python
python:
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
env:
  - DJANGO_VERSION=1.6.5

install:
  - apt-get install python-pip3
  - pip3 install pillow
  - pip3 install -q Django==$DJANGO_VERSION
  - apt-get install gettext
  - pip3 install pymysql
  - pip3 install djangorestframework
  - pip3 install markdown
  - pip3 install django-filter
  - pip3 install django-nose
  - pip3 install django-bootstrap-form
  - pip3 install pytz
  - pip3 install django-taggit
  - pip3 install grappelli
  - pip3 install south
  - pip3 install -q Django==$DJANGO_VERSION
 
  
# command to run tests
script: python3.4 ./manage.py test


  