language: python
python:
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
env:
  - DJANGO_VERSION=1.6.5

install:
  - pip install pillow
  - pip install -q Django==$DJANGO_VERSION
  - apt-get install gettext
  - pip install pymysql
  - pip install djangorestframework
  - pip install markdown
  - pip install django-filter
  - pip install django-nose
  - pip install django-bootstrap-form
  - pip install pytz
  - pip install django-taggit
  - pip install grappelli
  - pip install south
  - pip install -q Django==$DJANGO_VERSION
 
  
# command to run tests
script: python3.4 ./manage.py test


  